
CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) UNIQUE NOT NULL,
	first_name TINYTEXT NOT NULL,
	last_name TINYTEXT NOT NULL,
	password TINYTEXT NOT NULL,
	job_title TINYTEXT,
	business_sector TINYTEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

